[package]
name = "qmc-decode"
version = "0.1.0"
authors = ["Hongze Xia <hongze.x@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
glob = "0.3.0"